name: uw-workshop-training
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.10
  - pip
  - pip:
      - azureml-core==1.57.0.post1
      - azureml-dataprep==5.1.6
      - azureml-dataprep-native==41.0.0
      - azureml-dataprep-rslex==2.22.4
      - azureml-fsspec==1.3.1
      - azureml-mlflow==1.57.0.post1
      - azureml-mlflow==1.57.0.post1
      - mlflow==2.16.2
      - mlflow-skinny==2.16.2
      - pandas<2.0.0
      - torch~=2.6.0
      - torchvision~=0.21.0
      - pytorch-lightning<2.0.0
      - pydicom~=2.4.0
      - Pillow>=9.4.0
      - torchxrayvision~=1.3.0
      - numpy<2.0

